// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core_util.proto

package com.dingding.octopus.rpc.common;

public final class CoreUtilProto {
  private CoreUtilProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerInformationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.ServerInformation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Server UUId
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    String getId();
    /**
     * <pre>
     *Server UUId
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional int32 type = 2;</code>
     */
    int getType();

    /**
     * <pre>
     *Server name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    String getName();
    /**
     * <pre>
     *Server name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *Server current time
     * </pre>
     *
     * <code>optional int64 time = 4;</code>
     */
    long getTime();

    /**
     * <pre>
     *Server message seq
     * </pre>
     *
     * <code>optional int64 seq = 5;</code>
     */
    long getSeq();

    /**
     * <pre>
     *Server load
     * </pre>
     *
     * <code>optional int32 load = 6;</code>
     */
    int getLoad();

    /**
     * <pre>
     *Addon message
     * </pre>
     *
     * <code>optional string message = 7;</code>
     */
    String getMessage();
    /**
     * <pre>
     *Addon message
     * </pre>
     *
     * <code>optional string message = 7;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>map&lt;string, string&gt; services = 8;</code>
     */
    int getServicesCount();
    /**
     * <code>map&lt;string, string&gt; services = 8;</code>
     */
    boolean containsServices(
            String key);
    /**
     * Use {@link #getServicesMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getServices();
    /**
     * <code>map&lt;string, string&gt; services = 8;</code>
     */
    java.util.Map<String, String>
    getServicesMap();
    /**
     * <code>map&lt;string, string&gt; services = 8;</code>
     */

    String getServicesOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; services = 8;</code>
     */

    String getServicesOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code core.ServerInformation}
   */
  public  static final class ServerInformation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.ServerInformation)
      ServerInformationOrBuilder {
    // Use ServerInformation.newBuilder() to construct.
    private ServerInformation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerInformation() {
      id_ = "";
      type_ = 0;
      name_ = "";
      time_ = 0L;
      seq_ = 0L;
      load_ = 0;
      message_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServerInformation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              type_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 32: {

              time_ = input.readInt64();
              break;
            }
            case 40: {

              seq_ = input.readInt64();
              break;
            }
            case 48: {

              load_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                services_ = com.google.protobuf.MapField.newMapField(
                    ServicesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000080;
              }
              com.google.protobuf.MapEntry<String, String>
              services = input.readMessage(
                  ServicesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              services_.getMutableMap().put(services.getKey(), services.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CoreUtilProto.internal_static_core_ServerInformation_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetServices();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CoreUtilProto.internal_static_core_ServerInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServerInformation.class, Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <pre>
     *Server UUId
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Server UUId
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;
    /**
     * <pre>
     *Server name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Server name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private long time_;
    /**
     * <pre>
     *Server current time
     * </pre>
     *
     * <code>optional int64 time = 4;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int SEQ_FIELD_NUMBER = 5;
    private long seq_;
    /**
     * <pre>
     *Server message seq
     * </pre>
     *
     * <code>optional int64 seq = 5;</code>
     */
    public long getSeq() {
      return seq_;
    }

    public static final int LOAD_FIELD_NUMBER = 6;
    private int load_;
    /**
     * <pre>
     *Server load
     * </pre>
     *
     * <code>optional int32 load = 6;</code>
     */
    public int getLoad() {
      return load_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 7;
    private volatile Object message_;
    /**
     * <pre>
     *Addon message
     * </pre>
     *
     * <code>optional string message = 7;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Addon message
     * </pre>
     *
     * <code>optional string message = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICES_FIELD_NUMBER = 8;
    private static final class ServicesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  CoreUtilProto.internal_static_core_ServerInformation_ServicesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> services_;
    private com.google.protobuf.MapField<String, String>
    internalGetServices() {
      if (services_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ServicesDefaultEntryHolder.defaultEntry);
      }
      return services_;
    }

    public int getServicesCount() {
      return internalGetServices().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; services = 8;</code>
     */

    public boolean containsServices(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetServices().getMap().containsKey(key);
    }
    /**
     * Use {@link #getServicesMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getServices() {
      return getServicesMap();
    }
    /**
     * <code>map&lt;string, string&gt; services = 8;</code>
     */

    public java.util.Map<String, String> getServicesMap() {
      return internalGetServices().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; services = 8;</code>
     */

    public String getServicesOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetServices().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; services = 8;</code>
     */

    public String getServicesOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetServices().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (type_ != 0) {
        output.writeInt32(2, type_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (time_ != 0L) {
        output.writeInt64(4, time_);
      }
      if (seq_ != 0L) {
        output.writeInt64(5, seq_);
      }
      if (load_ != 0) {
        output.writeInt32(6, load_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, message_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetServices().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        services = ServicesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(8, services);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, time_);
      }
      if (seq_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, seq_);
      }
      if (load_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, load_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, message_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetServices().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        services = ServicesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, services);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServerInformation)) {
        return super.equals(obj);
      }
      ServerInformation other = (ServerInformation) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getType()
          == other.getType());
      result = result && getName()
          .equals(other.getName());
      result = result && (getTime()
          == other.getTime());
      result = result && (getSeq()
          == other.getSeq());
      result = result && (getLoad()
          == other.getLoad());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && internalGetServices().equals(
          other.internalGetServices());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeq());
      hash = (37 * hash) + LOAD_FIELD_NUMBER;
      hash = (53 * hash) + getLoad();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (!internalGetServices().getMap().isEmpty()) {
        hash = (37 * hash) + SERVICES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetServices().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServerInformation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerInformation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerInformation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerInformation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerInformation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServerInformation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServerInformation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServerInformation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServerInformation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServerInformation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServerInformation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.ServerInformation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.ServerInformation)
        ServerInformationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CoreUtilProto.internal_static_core_ServerInformation_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetServices();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMutableServices();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CoreUtilProto.internal_static_core_ServerInformation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServerInformation.class, Builder.class);
      }

      // Construct using com.dingding.octopus.rpc.common.CoreUtilProto.ServerInformation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        type_ = 0;

        name_ = "";

        time_ = 0L;

        seq_ = 0L;

        load_ = 0;

        message_ = "";

        internalGetMutableServices().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CoreUtilProto.internal_static_core_ServerInformation_descriptor;
      }

      public ServerInformation getDefaultInstanceForType() {
        return ServerInformation.getDefaultInstance();
      }

      public ServerInformation build() {
        ServerInformation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ServerInformation buildPartial() {
        ServerInformation result = new ServerInformation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.type_ = type_;
        result.name_ = name_;
        result.time_ = time_;
        result.seq_ = seq_;
        result.load_ = load_;
        result.message_ = message_;
        result.services_ = internalGetServices();
        result.services_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServerInformation) {
          return mergeFrom((ServerInformation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServerInformation other) {
        if (other == ServerInformation.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getSeq() != 0L) {
          setSeq(other.getSeq());
        }
        if (other.getLoad() != 0) {
          setLoad(other.getLoad());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        internalGetMutableServices().mergeFrom(
            other.internalGetServices());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServerInformation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServerInformation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object id_ = "";
      /**
       * <pre>
       *Server UUId
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *Server UUId
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Server UUId
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Server UUId
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Server UUId
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 2;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       *Server name
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *Server name
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Server name
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Server name
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Server name
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *Server current time
       * </pre>
       *
       * <code>optional int64 time = 4;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *Server current time
       * </pre>
       *
       * <code>optional int64 time = 4;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Server current time
       * </pre>
       *
       * <code>optional int64 time = 4;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private long seq_ ;
      /**
       * <pre>
       *Server message seq
       * </pre>
       *
       * <code>optional int64 seq = 5;</code>
       */
      public long getSeq() {
        return seq_;
      }
      /**
       * <pre>
       *Server message seq
       * </pre>
       *
       * <code>optional int64 seq = 5;</code>
       */
      public Builder setSeq(long value) {
        
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Server message seq
       * </pre>
       *
       * <code>optional int64 seq = 5;</code>
       */
      public Builder clearSeq() {
        
        seq_ = 0L;
        onChanged();
        return this;
      }

      private int load_ ;
      /**
       * <pre>
       *Server load
       * </pre>
       *
       * <code>optional int32 load = 6;</code>
       */
      public int getLoad() {
        return load_;
      }
      /**
       * <pre>
       *Server load
       * </pre>
       *
       * <code>optional int32 load = 6;</code>
       */
      public Builder setLoad(int value) {
        
        load_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Server load
       * </pre>
       *
       * <code>optional int32 load = 6;</code>
       */
      public Builder clearLoad() {
        
        load_ = 0;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <pre>
       *Addon message
       * </pre>
       *
       * <code>optional string message = 7;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *Addon message
       * </pre>
       *
       * <code>optional string message = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Addon message
       * </pre>
       *
       * <code>optional string message = 7;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Addon message
       * </pre>
       *
       * <code>optional string message = 7;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Addon message
       * </pre>
       *
       * <code>optional string message = 7;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> services_;
      private com.google.protobuf.MapField<String, String>
      internalGetServices() {
        if (services_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ServicesDefaultEntryHolder.defaultEntry);
        }
        return services_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableServices() {
        onChanged();;
        if (services_ == null) {
          services_ = com.google.protobuf.MapField.newMapField(
              ServicesDefaultEntryHolder.defaultEntry);
        }
        if (!services_.isMutable()) {
          services_ = services_.copy();
        }
        return services_;
      }

      public int getServicesCount() {
        return internalGetServices().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; services = 8;</code>
       */

      public boolean containsServices(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetServices().getMap().containsKey(key);
      }
      /**
       * Use {@link #getServicesMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getServices() {
        return getServicesMap();
      }
      /**
       * <code>map&lt;string, string&gt; services = 8;</code>
       */

      public java.util.Map<String, String> getServicesMap() {
        return internalGetServices().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; services = 8;</code>
       */

      public String getServicesOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetServices().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; services = 8;</code>
       */

      public String getServicesOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetServices().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearServices() {
        getMutableServices().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; services = 8;</code>
       */

      public Builder removeServices(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        getMutableServices().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableServices() {
        return internalGetMutableServices().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; services = 8;</code>
       */
      public Builder putServices(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        getMutableServices().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; services = 8;</code>
       */

      public Builder putAllServices(
          java.util.Map<String, String> values) {
        getMutableServices().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:core.ServerInformation)
    }

    // @@protoc_insertion_point(class_scope:core.ServerInformation)
    private static final ServerInformation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServerInformation();
    }

    public static ServerInformation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerInformation>
        PARSER = new com.google.protobuf.AbstractParser<ServerInformation>() {
      public ServerInformation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerInformation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerInformation> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServerInformation> getParserForType() {
      return PARSER;
    }

    public ServerInformation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientInformationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.ClientInformation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Client UUId
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    String getId();
    /**
     * <pre>
     *Client UUId
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional int32 type = 2;</code>
     */
    int getType();

    /**
     * <pre>
     *Client name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    String getName();
    /**
     * <pre>
     *Client name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *Client current time
     * </pre>
     *
     * <code>optional int64 time = 4;</code>
     */
    long getTime();

    /**
     * <pre>
     *Client message seq
     * </pre>
     *
     * <code>optional int64 seq = 5;</code>
     */
    long getSeq();

    /**
     * <pre>
     *Addon message
     * </pre>
     *
     * <code>optional string message = 6;</code>
     */
    String getMessage();
    /**
     * <pre>
     *Addon message
     * </pre>
     *
     * <code>optional string message = 6;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code core.ClientInformation}
   */
  public  static final class ClientInformation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.ClientInformation)
      ClientInformationOrBuilder {
    // Use ClientInformation.newBuilder() to construct.
    private ClientInformation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientInformation() {
      id_ = "";
      type_ = 0;
      name_ = "";
      time_ = 0L;
      seq_ = 0L;
      message_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClientInformation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              type_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 32: {

              time_ = input.readInt64();
              break;
            }
            case 40: {

              seq_ = input.readInt64();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CoreUtilProto.internal_static_core_ClientInformation_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CoreUtilProto.internal_static_core_ClientInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientInformation.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <pre>
     *Client UUId
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Client UUId
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;
    /**
     * <pre>
     *Client name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Client name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private long time_;
    /**
     * <pre>
     *Client current time
     * </pre>
     *
     * <code>optional int64 time = 4;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int SEQ_FIELD_NUMBER = 5;
    private long seq_;
    /**
     * <pre>
     *Client message seq
     * </pre>
     *
     * <code>optional int64 seq = 5;</code>
     */
    public long getSeq() {
      return seq_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 6;
    private volatile Object message_;
    /**
     * <pre>
     *Addon message
     * </pre>
     *
     * <code>optional string message = 6;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Addon message
     * </pre>
     *
     * <code>optional string message = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (type_ != 0) {
        output.writeInt32(2, type_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (time_ != 0L) {
        output.writeInt64(4, time_);
      }
      if (seq_ != 0L) {
        output.writeInt64(5, seq_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, time_);
      }
      if (seq_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, seq_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientInformation)) {
        return super.equals(obj);
      }
      ClientInformation other = (ClientInformation) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getType()
          == other.getType());
      result = result && getName()
          .equals(other.getName());
      result = result && (getTime()
          == other.getTime());
      result = result && (getSeq()
          == other.getSeq());
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeq());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientInformation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientInformation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientInformation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientInformation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientInformation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientInformation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientInformation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ClientInformation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientInformation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientInformation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientInformation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.ClientInformation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.ClientInformation)
        ClientInformationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CoreUtilProto.internal_static_core_ClientInformation_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CoreUtilProto.internal_static_core_ClientInformation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientInformation.class, Builder.class);
      }

      // Construct using com.dingding.octopus.rpc.common.CoreUtilProto.ClientInformation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        type_ = 0;

        name_ = "";

        time_ = 0L;

        seq_ = 0L;

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CoreUtilProto.internal_static_core_ClientInformation_descriptor;
      }

      public ClientInformation getDefaultInstanceForType() {
        return ClientInformation.getDefaultInstance();
      }

      public ClientInformation build() {
        ClientInformation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientInformation buildPartial() {
        ClientInformation result = new ClientInformation(this);
        result.id_ = id_;
        result.type_ = type_;
        result.name_ = name_;
        result.time_ = time_;
        result.seq_ = seq_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientInformation) {
          return mergeFrom((ClientInformation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientInformation other) {
        if (other == ClientInformation.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getSeq() != 0L) {
          setSeq(other.getSeq());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientInformation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientInformation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <pre>
       *Client UUId
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *Client UUId
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Client UUId
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Client UUId
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Client UUId
       * </pre>
       *
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 2;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       *Client name
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *Client name
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Client name
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Client name
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Client name
       * </pre>
       *
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *Client current time
       * </pre>
       *
       * <code>optional int64 time = 4;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *Client current time
       * </pre>
       *
       * <code>optional int64 time = 4;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Client current time
       * </pre>
       *
       * <code>optional int64 time = 4;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private long seq_ ;
      /**
       * <pre>
       *Client message seq
       * </pre>
       *
       * <code>optional int64 seq = 5;</code>
       */
      public long getSeq() {
        return seq_;
      }
      /**
       * <pre>
       *Client message seq
       * </pre>
       *
       * <code>optional int64 seq = 5;</code>
       */
      public Builder setSeq(long value) {
        
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Client message seq
       * </pre>
       *
       * <code>optional int64 seq = 5;</code>
       */
      public Builder clearSeq() {
        
        seq_ = 0L;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <pre>
       *Addon message
       * </pre>
       *
       * <code>optional string message = 6;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *Addon message
       * </pre>
       *
       * <code>optional string message = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Addon message
       * </pre>
       *
       * <code>optional string message = 6;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Addon message
       * </pre>
       *
       * <code>optional string message = 6;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Addon message
       * </pre>
       *
       * <code>optional string message = 6;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:core.ClientInformation)
    }

    // @@protoc_insertion_point(class_scope:core.ClientInformation)
    private static final ClientInformation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientInformation();
    }

    public static ClientInformation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientInformation>
        PARSER = new com.google.protobuf.AbstractParser<ClientInformation>() {
      public ClientInformation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientInformation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientInformation> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClientInformation> getParserForType() {
      return PARSER;
    }

    public ClientInformation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_ServerInformation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_ServerInformation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_ServerInformation_ServicesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_ServerInformation_ServicesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_ClientInformation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_ClientInformation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017core_util.proto\022\004core\"\337\001\n\021ServerInform" +
      "ation\022\n\n\002id\030\001 \001(\t\022\014\n\004type\030\002 \001(\005\022\014\n\004name\030" +
      "\003 \001(\t\022\014\n\004time\030\004 \001(\003\022\013\n\003seq\030\005 \001(\003\022\014\n\004load" +
      "\030\006 \001(\005\022\017\n\007message\030\007 \001(\t\0227\n\010services\030\010 \003(" +
      "\0132%.core.ServerInformation.ServicesEntry" +
      "\032/\n\rServicesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001\"g\n\021ClientInformation\022\n\n\002id\030\001 \001" +
      "(\t\022\014\n\004type\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\014\n\004time\030\004" +
      " \001(\003\022\013\n\003seq\030\005 \001(\003\022\017\n\007message\030\006 \001(\t2T\n\rRp" +
      "cServerUtil\022C\n\tHeartBeat\022\027.core.ClientIn",
      "formation\032\027.core.ServerInformation\"\000(\0010\001" +
      "B7\n\037com.dingding.octopus.rpc.commonB\rCor" +
      "eUtilProtoP\000\242\002\002CUb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_core_ServerInformation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_ServerInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_ServerInformation_descriptor,
        new String[] { "Id", "Type", "Name", "Time", "Seq", "Load", "Message", "Services", });
    internal_static_core_ServerInformation_ServicesEntry_descriptor =
      internal_static_core_ServerInformation_descriptor.getNestedTypes().get(0);
    internal_static_core_ServerInformation_ServicesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_ServerInformation_ServicesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_core_ClientInformation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_core_ClientInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_ClientInformation_descriptor,
        new String[] { "Id", "Type", "Name", "Time", "Seq", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
